apiVersion: apps/v1
kind: Deployment
metadata:
  name: dlcbld-demo
  labels:
    app: dlcbld-demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dlcbld-demo
  template:
    metadata:
      labels:
        app: dlcbld-demo
    spec:
      containers:
        - name: dlcbld-demo
          imagePullPolicy: Always
          image: phx.ocir.io/axsewmzamo2h/dlcbld-demo:${BuildServiceDemoVersion}
          ports:
            - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: dlcbld-demo
  labels:
    app: dlcbld-demo
spec:
  type: LoadBalancer
  ports:
    - port: 8081
      targetPort: 8081
  selector:
    app: dlcbld-demo
